### ISSUE TITLE
What do your Apple shortcuts look like?

### ISSUE THREAD

**Issue by zinzy** [muan/site#45]
I've been struggling with micropub as of late, and I'm interested in your approach to publishing. Would you be willing to share the Apple shortcuts you use?

**Comment by muan** [comment]
Do you mean specifically for notes? [This is the GitHub Action](https://github.com/muan/site/blob/main/.github/workflows/notes.yml), which runs [this script](https://github.com/muan/site/blob/ff113b5db4d5f282c751f81f5c62d06e2f986abe/.github/workflows/scripts/notes.js) mostly because I don't know how to write shell scripts, otherwise JS wouldn't be needed. And with Apple Shourtcuts + [the GitHub App on iOS](https://github.com/mobile), you can trigger a [`workflow_dispatch`](https://github.com/muan/site/blob/ff113b5db4d5f282c751f81f5c62d06e2f986abe/.github/workflows/notes.yml#L4) with inputs. So my shortcut prompts me for text, and get current date, format it, and send it along with the workflow_dispatch. That's it. 

<img alt="screenshot of apple shortcut script showing the aforementioned steps" width="400" src="https://user-images.githubusercontent.com/1153134/234156829-90d26e08-a66e-49f1-a76d-bc280da30ecd.jpeg">

**Comment by sheriferson** [comment]
(Came here via the [2023-04-25 note](https://muan.co/notes/2023-04-25-uu). Not sure where best to leave this other than the closed issue, hopefully here is good)

I also use Jekyll for my microblog and an iOS Shortcut to publish to it. [Wrote about the setup here](https://sherif.io/2023/03/02/shortcut-bulletin.html).

Benefits: No need for shell scripts or node installation.
It does rely on the Working Copy iOS app for making and pushing the commits and Netlify for building and serving the site. I don't know if the GitHub iOS app can be a sufficient replacement for Working Copy, but I'm sharing the post nonetheless in case it's useful.

**Comment by muan** [comment]
@sheriferson thanks for sharing! 

WRT timzeons, I get iOS to get me ISO 8601, which will be 2023-04-29T06:39:01+08:00.

But I think [with custom format you can get TZ name with `zzz`](https://support.apple.com/guide/shortcuts/custom-date-formats-apd8d9b19184/ios).

<img width="616" alt="" src="https://user-images.githubusercontent.com/1153134/235381216-d52bbb0e-c155-4402-83ea-b9e7310f8096.png">

Did that not work for you?

---

Also, GitHub should totally build writing a file to a repository as one of their shortcuts :). I am tempted to cc my ex-hubber friends here but I will refrain myself. 😅

**Comment by sheriferson** [comment]
Yeah, you are correct, you can get `PDT` or `EST` from iOS, but I'm looking for what they refer to as [time zone ID](https://unicode.org/reports/tr35/tr35-dates.html#Time_Zone_Names) or [TZ identifier](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones), e.g., `America/Los_Angeles`. As far as I can tell I can't get that from iOS.

As for _why_ I want that, it's for a Jekyll plugin I wrote for my particular site that seems to require it (I say seems because I barely know Ruby so it's possible I can get what I want done with just `PDT`). In any case, that's a special need for my site and shouldn't impact most people.

---

hah, or maybe you can just beg to get write access to the iOS repo for just a weekend for old times' sake, DIY!
