### ISSUE TITLE
🖼️ Add some screenshots in the README.

### ISSUE THREAD

**Issue by thedipankarroy** [muan/site#46]
Awesome work, I mean. I initially assumed it was a basic HTML project, but the blinking colon was what sparked questions.

I am curious as to why you chose this simple but unique style.

**Comment by muan** [comment]
I am not good at using colors and even though at times I want fancy styles my I always convince myself not to. Partly because I don't think adding animation/other fanciness without clear purpose is a good use of my time, and partly because I am not so good at it, and the latter causes me to continue to not be good at it. However, I am really confident in my ability to execute a simple, concise, boring design. And I think it's no coincidence that this website conveys my personality quite well.

[Paco](https://paco.me/) has a similar aesthetic that sometimes I'd like to copy, but I think it felt a bit too sterile for my identity. I am not that polished.
[Javier](https://javier.computer/) also has a "simple" website, but with a lot of colors, and in fact, tons of tiny details go into it. I think they are a ton of fun. But I am not fun.
[Monica](https://meowni.ca/) too, has a clean website, but with tons of creativity sprinkled on top of it, and her arts. I don't do that. And once again, I am bad at doing colors. 

So this is what I end up with, and I am happy with it.

I don't really want to add screenshots though, because the website is a living thing. Everything changes all the time and I want to spare myself from having the update the screenshots. 

Thank you for the question.
